version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1